# Generated by Django 5.2 on 2025-04-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
