# Generated by Django 5.2 on 2025-06-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
